databases:
  - name: content-api-db
    databaseName: content_api
    user: content_user

services:
  - type: web
    name: content-api
    env: python
    rootDir: content_api
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn content_api.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: content-api-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: content_api.settings.production
